#!/usr/bin/env ruby
# =============================================================================
# encode.rb — Step 2: Run full encode pipeline from YAML config
# =============================================================================
# Takes a source MKV and a YAML config (generated by Claude via analyse.rb)
# and runs the full pipeline:
#   1. Strip/convert audio
#   2. Encode video with x265
#   3. Extract & inject Dolby Vision RPU (if needed)
#   4. Final remux
#
# Requirements:
#   ffmpeg (with libx265)
#   mediainfo
#   dovi_tool     — https://github.com/quietvoid/dovi_tool/releases
#   mkvtoolnix    — brew install mkvtoolnix / apt install mkvtoolnix
#
# Usage:
#   ruby encode.rb --file "Movie.mkv" --config "Movie_config.yaml"
#   ruby encode.rb --file "Movie.mkv" --config "Movie_config.yaml" --output-dir /output
#   ruby encode.rb --file "Movie.mkv" --config "Movie_config.yaml" --dry-run
#
# Options:
#   --file PATH          Source MKV file (required)
#   --config PATH        YAML config from Claude (required)
#   --output-dir PATH    Output directory (default: same as input file)
#   --output-name NAME   Override output filename
#   --crf N              Override CRF from config (lower = higher quality; 16–20 for high VMAF)
#   --dry-run            Show what would run, do not encode
#   --keep-temp          Keep intermediate files after completion
#   --yes, -y            Auto-confirm all prompts (overwrite existing output,
#                         proceed with encode) — for unattended/batch runs
# =============================================================================

require 'optparse'
require 'open3'
require 'fileutils'
require 'time'
require 'yaml'

# =============================================================================
# COLOURS
# =============================================================================

module C
  RESET  = "\033[0m"
  BOLD   = "\033[1m"
  DIM    = "\033[2m"
  RED    = "\033[91m"
  GREEN  = "\033[92m"
  YELLOW = "\033[93m"
  CYAN   = "\033[96m"
  WHITE  = "\033[97m"
  BLUE   = "\033[94m"
end

def c(text, *codes) = "#{codes.join}#{text}#{C::RESET}"
def log_ok(msg)     = puts(c("  ✓  #{msg}", C::GREEN))
def log_warn(msg)   = puts(c("  ⚠  #{msg}", C::YELLOW))
def log_info(msg)   = puts(c("  ℹ  #{msg}", C::BLUE))
def log_dim(msg)    = puts(c("     #{msg}", C::DIM))
def log_error(msg)  = (puts(c("  ✗  #{msg}", C::RED)); exit 1)
def log_section(t)  = puts("\n#{c("── #{t}", C::CYAN, C::BOLD)}")

def log_step(n, total, msg)
  puts "\n#{c("[#{n}/#{total}]", C::BOLD, C::WHITE)} #{c(msg, C::CYAN, C::BOLD)}"
end

# =============================================================================
# OPTIONS
# =============================================================================

options = { dry_run: false, keep_temp: false, yes: false }

OptionParser.new do |opts|
  opts.banner = "Usage: ruby encode.rb --file INPUT.mkv --config CONFIG.yaml [options]"
  opts.on('--file PATH',        'Source MKV file (required)')                { |v| options[:file]        = v }
  opts.on('--config PATH',      'YAML config from Claude (required)')        { |v| options[:config]      = v }
  opts.on('--output-dir PATH',  'Output directory (default: same as input)') { |v| options[:output_dir]  = v }
  opts.on('--output-name NAME', 'Override output filename')                  { |v| options[:output_name] = v }
  opts.on('--crf N',            'Override CRF from config (lower = better quality)') { |v| options[:crf] = v }
  opts.on('--dry-run',          'Show commands, do not encode')              { options[:dry_run]         = true }
  opts.on('--keep-temp',        'Keep intermediate files')                   { options[:keep_temp]       = true }
  opts.on('-y', '--yes',        'Auto-confirm all prompts (for unattended/batch runs)') { options[:yes] = true }
  opts.on('--help', 'Show help') { puts opts; exit }
end.parse!

log_error("--file is required")   unless options[:file]
log_error("--config is required") unless options[:config]
log_error("File not found: #{options[:file]}")     unless File.exist?(options[:file])
log_error("Config not found: #{options[:config]}") unless File.exist?(options[:config])

# =============================================================================
# LOAD CONFIG
# =============================================================================

begin
  cfg = YAML.safe_load(File.read(options[:config]), permitted_classes: [Symbol])
rescue => e
  log_error("Failed to parse YAML config: #{e.message}")
end

cfg = cfg.transform_keys(&:to_s)

if options[:crf]
  crf = options[:crf].to_i
  log_error("--crf must be between 0 and 51") unless (0..51).include?(crf)
  cfg['crf_override'] = cfg['crf']
  cfg['crf'] = crf
end

# =============================================================================
# FILE PATHS
# =============================================================================

INPUT      = File.expand_path(options[:file])
BASENAME   = File.basename(INPUT, File.extname(INPUT))
OUTPUT_DIR = options[:output_dir] ? File.expand_path(options[:output_dir]) : File.dirname(INPUT)

FileUtils.mkdir_p(OUTPUT_DIR)

TIMESTAMP       = Time.now.strftime('%Y%m%d_%H%M%S')
TEMP_DIR        = File.join(OUTPUT_DIR, ".encode_tmp_#{TIMESTAMP}")
TEMP_AUDIO      = File.join(TEMP_DIR, "#{BASENAME}_audio.mkv")
TEMP_VIDEO_HEVC = File.join(TEMP_DIR, "#{BASENAME}_video.hevc")
TEMP_VIDEO_DV   = File.join(TEMP_DIR, "#{BASENAME}_video_dv.hevc")
TEMP_RPU        = File.join(TEMP_DIR, "#{BASENAME}_rpu.bin")
LOG_FILE        = File.join(OUTPUT_DIR, "#{BASENAME}_encode_#{TIMESTAMP}.log")

output_name = options[:output_name] || "#{BASENAME}_x265_crf#{cfg['crf']}.mkv"
OUTPUT_FILE = File.join(OUTPUT_DIR, output_name)

# =============================================================================
# HELPERS
# =============================================================================

def command_exists?(cmd)
  system("which #{cmd} > /dev/null 2>&1")
end

def run_cmd(cmd, label, log_file, dry_run: false)
  log_dim("$ #{cmd.join(' ')}")
  if dry_run
    log_dim("[dry-run — not executed]")
    return true
  end

  File.open(log_file, 'a') { |f| f.puts "\n[#{Time.now}] #{label}\n#{cmd.join(' ')}\n" }

  Open3.popen2e(*cmd) do |_stdin, stdout_err, wait_thr|
    buf = +''
    loop do
      begin
        buf += stdout_err.readpartial(4096)
      rescue EOFError
        break
      end
      # flush complete lines split on \r or \n — progress lines use \r, not \n
      while (idx = buf.index(/[\r\n]/))
        line = buf.slice!(0, idx + 1).chomp
        next if line.empty?
        File.open(log_file, 'a') { |f| f.puts line }
        if line =~ /frame=|time=|size=|speed=/
          $stderr.print "\r     #{line[0..120]}"
          $stderr.flush
        elsif line =~ /^\s*\d+ frames:/
          $stderr.print "\r     #{line[0..120]}"
          $stderr.flush
        elsif line =~ /x265 \[error\]|Error(?!.*skipping)|failed/i
          $stderr.puts ''
          log_warn(line)
        end
      end
    end
    File.open(log_file, 'a') { |f| f.puts buf } unless buf.strip.empty?
    $stderr.puts ''
    return wait_thr.value.success?
  end
end

def confirm(prompt, auto: false)
  if auto
    log_dim("#{prompt} [y/N] auto-confirmed (--yes)")
    return true
  end
  print "\n#{c("  ? ", C::YELLOW, C::BOLD)}#{c(prompt, C::WHITE)} #{c("[y/N] ", C::DIM)}"
  r = $stdin.gets.chomp.downcase
  r == 'y' || r == 'yes'
end

def validate_config!(cfg)
  required = %w[crf preset audio_stream audio_action has_dv is_sdr]
  missing  = required.reject { |k| cfg.key?(k) }
  log_error("Config missing required fields: #{missing.join(', ')}") unless missing.empty?
  valid_actions = %w[dts_core copy convert_ac3 convert_aac]
  unless valid_actions.include?(cfg['audio_action'])
    log_error("Invalid audio_action '#{cfg['audio_action']}'. Must be one of: #{valid_actions.join(', ')}")
  end
end

# =============================================================================
# DISPLAY SUMMARY
# =============================================================================

def display_summary(cfg, input, output)
  puts
  puts c('=' * 60, C::BOLD)
  puts c('  Encode Plan', C::BOLD, C::WHITE)
  puts c('=' * 60, C::BOLD)
  puts "  #{c('Input:', C::DIM)}       #{File.basename(input)}"
  puts "  #{c('Output:', C::DIM)}      #{File.basename(output)}"
  puts "  #{c('Resolution:', C::DIM)}  #{cfg['resolution'] || 'unknown'}"
  puts "  #{c('HDR:', C::DIM)}         #{cfg['hdr'] || 'unknown'}"
  crf_label = cfg['crf_override'] ? "#{cfg['crf']} #{c("(overrides config: #{cfg['crf_override']})", C::YELLOW)}" : cfg['crf']
  puts "  #{c('CRF:', C::DIM)}         #{crf_label}"
  puts "  #{c('Preset:', C::DIM)}      #{cfg['preset']}"
  puts "  #{c('Audio:', C::DIM)}       #{cfg['audio_description'] || cfg['audio_action']} (stream #{cfg['audio_stream']})"
  dv_status = if cfg['has_dv']
    cfg['dv_profile_conversion_needed'] ? 'Yes — 7.6 → 8.1 conversion' : 'Yes — Profile 8.1, no conversion'
  else
    'No'
  end
  puts "  #{c('DV:', C::DIM)}          #{dv_status}"
  puts "  #{c('Subtitles:', C::DIM)}   #{cfg['has_subtitles'] ? "#{(cfg['subtitle_streams'] || []).length} track(s)" : 'none'}"
  puts "  #{c('Cover art:', C::DIM)}   #{cfg['has_cover_art'] ? 'present (will be dropped)' : 'none'}"

  if cfg['warnings'] && !cfg['warnings'].empty?
    puts
    puts c('  Warnings:', C::YELLOW, C::BOLD)
    cfg['warnings'].each { |w| log_warn(w) }
  end

  puts c('=' * 60, C::BOLD)
end

# =============================================================================
# PIPELINE COMMANDS
# =============================================================================

def build_audio_cmd(cfg, input, temp_audio)
  action       = cfg['audio_action']
  audio_stream = cfg['audio_stream']
  has_subs     = cfg['has_subtitles']
  sub_streams  = cfg['subtitle_streams'] || []
  sub_maps     = has_subs ? sub_streams.flat_map { |s| ['-map', s] } : []

  base = %W[ffmpeg -analyzeduration 100M -probesize 100M -y -v warning -stats -i #{input}]

  case action
  when 'dts_core', 'copy'
    base + ['-map', '0:0', '-map', audio_stream] + sub_maps + %W[-c copy #{temp_audio}]
  when 'convert_ac3'
    bitrate = cfg['audio_convert_bitrate'] || '640k'
    base + ['-map', audio_stream] + sub_maps + %W[-c:a ac3 -b:a #{bitrate} -c:s copy #{temp_audio}]
  when 'convert_aac'
    bitrate = cfg['audio_convert_bitrate'] || '192k'
    base + ['-map', audio_stream] + sub_maps + %W[-c:a aac -b:a #{bitrate} -ac 2 -c:s copy #{temp_audio}]
  end
end

def build_video_cmd(cfg, input, temp_video)
  is_sdr = cfg['is_sdr']

  x265_params = if is_sdr
    'hdr-opt=0'
  else
    "hdr-opt=1:repeat-headers=1:" \
    "colorprim=#{cfg['color_primaries']}:" \
    "transfer=#{cfg['color_trc']}:" \
    "colormatrix=#{cfg['color_space']}:" \
    "master-display=#{cfg['master_display']}:" \
    "max-cll=#{cfg['max_cll']},#{cfg['max_fall']}"
  end

  pix_fmt = is_sdr ? 'yuv420p' : 'yuv420p10le'

  cmd = %W[ffmpeg -analyzeduration 100M -probesize 100M -y -v warning -stats
           -i #{input} -map 0:0
           -c:v libx265 -crf #{cfg['crf']} -preset #{cfg['preset']}
           -pix_fmt #{pix_fmt}
           -x265-params #{x265_params}]

  unless is_sdr
    cmd += %W[-color_primaries #{cfg['color_primaries']}
              -color_trc       #{cfg['color_trc']}
              -colorspace      #{cfg['color_space']}
              -color_range     #{cfg['color_range']}]
  end

  cmd + %W[-an -sn #{temp_video}]
end

def build_extract_rpu_cmd(cfg, input, temp_rpu)
  # RPU must be extracted from the original source -- it contains the HEVC video
  # track with embedded RPU NAL units. The audio MKV intermediate has no video.
  cfg['dv_profile_conversion_needed'] ?
    %W[dovi_tool -m 2 extract-rpu -i #{input} -o #{temp_rpu}] :
    %W[dovi_tool extract-rpu -i #{input} -o #{temp_rpu}]
end

def build_inject_rpu_cmd(temp_video, temp_rpu, temp_video_dv)
  %W[dovi_tool inject-rpu -i #{temp_video} --rpu-in #{temp_rpu} -o #{temp_video_dv}]
end

def build_remux_cmd(video_file, temp_audio, output_file)
  %W[mkvmerge -o #{output_file} #{video_file} --no-video #{temp_audio}]
end

# =============================================================================
# VERIFY OUTPUT
# =============================================================================

def verify_output(output_file)
  return unless File.exist?(output_file)
  stdout, _stderr, _status = Open3.capture3('mediainfo', output_file)
  relevant = stdout.split("\n").select { |l|
    ['HDR', 'Dolby', 'Bit rate', 'File size', 'Width', 'Height', 'Duration'].any? { |k| l.include?(k) }
  }.first(10)
  relevant.each { |l| log_dim(l.strip) }
end

# =============================================================================
# MAIN
# =============================================================================

puts
puts c('=' * 60, C::BOLD)
puts c('  encode.rb — Full Encode Pipeline', C::BOLD, C::WHITE)
puts c('  Audio → Video → DV → Remux', C::DIM)
puts c('=' * 60, C::BOLD)

log_section("Validating config")
validate_config!(cfg)
log_ok("Config valid")

log_section("Checking dependencies")
deps = %w[ffmpeg ffprobe mkvmerge]
deps << 'dovi_tool' if cfg['has_dv']
deps.each do |cmd|
  command_exists?(cmd) ? log_ok(cmd) : log_error("#{cmd} not found — please install it")
end

display_summary(cfg, INPUT, OUTPUT_FILE)

if File.exist?(OUTPUT_FILE) && !options[:dry_run]
  unless confirm("Output file already exists. Overwrite?", auto: options[:yes])
    log_info("Aborted.")
    exit 0
  end
end

unless options[:dry_run]
  unless confirm("Proceed with encode?", auto: options[:yes])
    log_info("Aborted.")
    exit 0
  end
end

FileUtils.mkdir_p(TEMP_DIR)
log_dim("Temp:   #{TEMP_DIR}")
log_dim("Log:    #{LOG_FILE}")
log_dim("Output: #{OUTPUT_FILE}")

start_time  = Time.now
has_dv      = cfg['has_dv']
total_steps = has_dv ? 5 : 3
final_video = has_dv ? TEMP_VIDEO_DV : TEMP_VIDEO_HEVC
dry         = options[:dry_run]

# Step 1: Audio
log_step(1, total_steps, "Audio: #{cfg['audio_action']} (stream #{cfg['audio_stream']})")
success = run_cmd(build_audio_cmd(cfg, INPUT, TEMP_AUDIO), "Audio", LOG_FILE, dry_run: dry)
log_error("Audio step failed — check #{LOG_FILE}") unless success || dry
log_ok("Audio complete") unless dry

# Step 2: Video
log_step(2, total_steps, "Video encode (CRF #{cfg['crf']}, #{cfg['preset']})")
log_warn("This will take a while — progress shown below") unless dry
success = run_cmd(build_video_cmd(cfg, INPUT, TEMP_VIDEO_HEVC), "Video", LOG_FILE, dry_run: dry)
log_error("Video encode failed — check #{LOG_FILE}") unless success || dry
log_ok("Video encode complete") unless dry

# Steps 3 & 4: DV
if has_dv
  log_step(3, total_steps, "Extract DV RPU#{cfg['dv_profile_conversion_needed'] ? ' (7.6 → 8.1)' : ''}")
  success = run_cmd(build_extract_rpu_cmd(cfg, INPUT, TEMP_RPU), "Extract RPU", LOG_FILE, dry_run: dry)
  log_error("RPU extraction failed — check #{LOG_FILE}") unless success || dry
  log_ok("RPU extracted") unless dry

  log_step(4, total_steps, "Inject DV RPU")
  success = run_cmd(build_inject_rpu_cmd(TEMP_VIDEO_HEVC, TEMP_RPU, TEMP_VIDEO_DV), "Inject RPU", LOG_FILE, dry_run: dry)
  log_error("RPU injection failed — check #{LOG_FILE}") unless success || dry
  log_ok("RPU injected") unless dry
end

# Final step: Remux
log_step(total_steps, total_steps, "Final remux")
success = run_cmd(build_remux_cmd(final_video, TEMP_AUDIO, OUTPUT_FILE), "Remux", LOG_FILE, dry_run: dry)
log_error("Remux failed — check #{LOG_FILE}") unless success || dry
log_ok("Remux complete") unless dry

if dry
  puts
  log_ok("Dry run complete — no files were modified")
  puts
else
  unless options[:keep_temp]
    log_section("Cleaning up")
    FileUtils.rm_rf(TEMP_DIR)
    log_ok("Temp files removed")
  end

  log_section("Output verification")
  verify_output(OUTPUT_FILE)

  elapsed = Time.now - start_time
  hours   = (elapsed / 3600).to_i
  mins    = ((elapsed % 3600) / 60).to_i
  secs    = (elapsed % 60).to_i

  puts
  puts c('=' * 60, C::BOLD)
  puts c('  Done!', C::BOLD, C::GREEN)
  puts c('=' * 60, C::BOLD)
  puts "  #{c('Input:', C::DIM)}   #{File.basename(INPUT)}"
  puts "  #{c('Output:', C::DIM)}  #{File.basename(OUTPUT_FILE)}"
  puts "  #{c('Time:', C::DIM)}    #{hours}h #{mins}m #{secs}s"

  if File.exist?(OUTPUT_FILE)
    input_size  = File.size(INPUT)
    output_size = File.size(OUTPUT_FILE)
    reduction   = ((1 - output_size.to_f / input_size) * 100).round(1)
    puts "  #{c('Size:', C::DIM)}    #{(input_size / 1_073_741_824.0).round(2)} GB → #{(output_size / 1_073_741_824.0).round(2)} GB (#{reduction}% reduction)"
  end

  puts c('=' * 60, C::BOLD)
  puts
end